name = "mailgofer"
main = "src/index.js"
compatibility_date = "2026-03-22"

[[routes]]
pattern = "api.qdp.qzz.io/*"
zone_name = "qdp.qzz.io"

[[routes]]
pattern = "send.qdp.qzz.io/*"
zone_name = "qdp.qzz.io"

[[d1_databases]]
binding = "DB"
database_name = "mail_api"
database_id = "8a2c55de-e379-4123-b789-391d5527f6d7"

[vars]
MAIL_DOMAIN = "mail.qdp.qzz.io"
API_TOKEN="1c8d216d80c50e4b33f0879422768ba67d1ca4b2df3a743aa6cab3a439a03775"
FORWARD_TO_EMAIL = "Lingion04@gmail.com"
